server:
  port: 9999
  servlet:
    context-path: /batman
spring:
  #  application:
  #    name: aklung
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/batman?&useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 111111
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
    static-locations: classpath:/static/,file:${cms.fileRootPath}
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/**.xml
  global-config:
    db-config:
      id-type: uuid
      table-prefix: cat_
      table-underline: true
  type-aliases-package: com.bigdata.coreweb.entity
  configuration:
    map-underscore-to-camel-case: true
cms:
  auth: false
  fileRootPath: E:/file/
  serverUrl: http://10.144.200.24:7333/
logging:
  level:
    com.bigdata.usercenter.mapper: debug
#  config-location: classpath:mybatis/mybatis-config.xml
